### ISSUE TITLE
LSPS2: Expiring of requests

### ISSUE THREAD

**Issue by johncantrell97** [lightningdevkit/lightning-liquidity#27]
There is this concept of `valid_until` in the opening fee params that specifies a datetime when this particular jit channel request becomes invalid.

We currently are not expiring requests.  We are only checking the validity at the time the buy request is made.  At a minimum we need:

1) A way to poll or regularly check if requests we are waiting on payment for have expired.
2) When htlc_interception happens we should make sure the request is still valid

**Comment by tnull** [comment]
As of https://github.com/lightningdevkit/rust-lightning/pull/3436 we now prune expired requests on peer disconnection and on block connection.
