### ISSUE TITLE
LSPS1: Potentially superfluous `GetOrderResponse`

### ISSUE THREAD

**Issue by tnull** [lightningdevkit/lightning-liquidity#66]
The LSP's response to a `GetOrderRequest` is the same object as to `CreateOrder`. I'm a bit dubious why we require it in a separate `GetOrderResponse` object.

**Comment by Srg213** [comment]
Yes I agree. I followed the naming convention in the spec and as mentioned, all of the fields of both `GetOrderResponse` and `CreateOrderResponse` are the same. LSP updates the order_status and channel parameters in the latter object.
Maybe the latter object should be pasesd as _mut_ and _*ref_, not sure.
