### ISSUE TITLE
It is possible to creat a LSPS2 client with this crate

### ISSUE THREAD

**Issue by yanganto** [lightningdevkit/lightning-liquidity#75]
After integration with `lightning-liquidity`, I believe the user will want a simple LSPS client to check the integration is well. The clients are public, but they can not really in used by any user because they are sealed.

For example, we have a public struct [`LSPS2ClientHandler`](https://github.com/lightningdevkit/lightning-liquidity/blob/587ffe78b6b966a6dcd9ae7fd64cb32c86d503c4/src/lsps2/client.rs#L203-L213), but the fields inside the struct are private and the new function is private (only public in the crate).
That is, the [`EventQueue`](https://github.com/lightningdevkit/lightning-liquidity/blob/587ffe78b6b966a6dcd9ae7fd64cb32c86d503c4/src/events.rs#L25) is private but it is required by `LSPS2ClientHandler`.

**Comment by tnull** [comment]
> After integration with `lightning-liquidity`, I believe the user will want a simple LSPS client to check the integration is well. The clients are public, but they can not really in used by any user because they are sealed.
> 
> For example, we have a public struct [`LSPS2ClientHandler`](https://github.com/lightningdevkit/lightning-liquidity/blob/587ffe78b6b966a6dcd9ae7fd64cb32c86d503c4/src/lsps2/client.rs#L203-L213), but the fields inside the struct are private and the new function is private (only public in the crate). That is, the [`EventQueue`](https://github.com/lightningdevkit/lightning-liquidity/blob/587ffe78b6b966a6dcd9ae7fd64cb32c86d503c4/src/events.rs#L25) is private but it is required by `LSPS2ClientHandler`.

Yes, constructors are (currently) intentionally hidden as LDK-based implementations will always need the `CustomMessageHandler` implemented by `LiquidityManager`, which currently is the main object of this library. The user might then access the sub-protocol handlers, e.g.,  via the the `lsps2_client_handler` accessor. 

Note that we're still in the middle of further modularizing and improving the API (cf. #69), and that the main reason for the message handler objects being individually exposed is that we intend to make them reusable even by non-LDK implementations, which is however not supported as of now.

**Comment by tnull** [comment]
Closing this as resolved, even though we might want to improve the API in the future.
